Fix trends in case of failures in contexts
In case when the context fails, there is no start_time timeframe in
workload and we should cover this case and do not fail with the next
error:

  TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

Closes-Bug: #1732193
Change-Id: I95e96bb98fe473e8c0ea910021966ceb203f35cd
(cherry picked from commit af2b146d243371fdff28b146fb85c5027b79aef4)