Fix incorrect __round__ behaviour
In some cases with large scenario parameters,
__round__ raises an error:

TypeError: type NoneType doesn't define __round__ method

Fix __round__ behaviour for StreamingAlgorithm ins == None.

Change-Id: I33acb494ddabc6855bd73868ebf8cbeee43bab86