Generate report at the end of rally-dsvm job
Seems like report can't be generated in 100% cases. Sometimes
it crashes with such message:

 RallyException: Unable to calculate the mean: no values processed so far.

It makes sense to genereate report after we get raw results, so it will
be possible to debug such cases locally.

Change-Id: I6d93617dfaf6d954a85b1428f828f7b57f6b6212